### ISSUE TITLE
Not compatible with kernel 4

### ISSUE THREAD

**Issue by Boldbrew** [jaredeh/axfs#4]
All the file->f_dentry->d_inode have to be replaced with file_inode(file). 
But this will not help with v4 due to lack of xip functions

fs/axfs/axfs_inode.c: In function ‘axfs_fault’:
fs/axfs/axfs_inode.c:598:3: error: implicit declaration of function ‘xip_file_fault’ [-Werror=implicit-function-declaration]
fs/axfs/axfs_inode.c: In function ‘axfs_file_read’:
fs/axfs/axfs_inode.c:739:4: error: implicit declaration of function ‘xip_file_read’ [-Werror=implicit-function-declaration]
fs/axfs/axfs_inode.c:744:4: error: implicit declaration of function ‘do_sync_read’ [-Werror=implicit-function-declaration]
fs/axfs/axfs_inode.c: At top level:
fs/axfs/axfs_inode.c:869:2: error: unknown field ‘get_xip_mem’ specified in initializer
fs/axfs/axfs_inode.c:869:2: warning: initialization from incompatible pointer type [enabled by default]
fs/axfs/axfs_inode.c:869:2: warning: (near initialization for ‘axfs_aops.writepages’) [enabled by default]
fs/axfs/axfs_inode.c:610:16: warning: ‘axfs_xip_file_read’ defined but not used [-Wunused-function]

**Comment by seebe** [comment]
Well....that stinks!

Looks like this is the reasoning behind all of the changes:
https://lkml.org/lkml/2014/9/25/620
https://lwn.net/Articles/618064/

My guess is that the functionality that AXFS needs is still in there, but renamed (XIP is now called DAX). You can see they made the necessary changes to ext2.
Unfortunately, it's not clear how much work it would be to switch over AXFS.

**Comment by jaredeh** [comment]
Thanks for bring this up.  I've reached out to the DAX guys.  It will take some time to get an officially supported version.  Post v4.5.  Short term just hacking filemap_xip.c back in will allow it to work.

**Comment by jaredeh** [comment]
Looks like @seebe fixed it finally!
